In [ ]:
import numpy as np

class Perceptron:

  def __init__(self, learning_rate=0.1):
    self.learning_rate = learning_rate
    self.weights = None
    self.bias = None

  def step(self, x):

    return np.where(x >= 0, 1, 0)

  def predict(self, X):

    activation = np.dot(X, self.weights) + self.bias
    return self.step(activation)

  def fit(self, X, y):

    self.weights = np.random.rand(X.shape[1])
    self.bias = 0
    epochs = 10

    for _ in range(epochs):
      for i, x in enumerate(X):
        predicted = self.predict(x.reshape(1, -1))
        error = y[i] - predicted
        self.weights += self.learning_rate * error * x
        self.bias += self.learning_rate * error


In [ ]:
or_gate = Perceptron()
X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_or = np.array([0, 1, 1, 1])
or_gate.fit(X_or, y_or)


In [ ]:
print("OR Gate Predictions:")
print(X_or)
print(or_gate.predict(X_or))


OR Gate Predictions:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 1]


In [ ]:
and_gate = Perceptron()
X_and = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])
and_gate.fit(X_and, y_and)


In [ ]:
print("\nAND Gate Predictions:")
print(X_and)
print(and_gate.predict(X_and))



AND Gate Predictions:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 0 0 1]
